name: Scheduled build

on:
  push
  # schedule:
  #   - cron: '* * * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: github contexts
        run: echo ${PWD}
      - name: mailsend
        run: |
          curl -v https://api.sendgrid.com/v3/mail/send \
          -H "Authorization: Bearer ${{ secrets.SG_APIKEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "personalizations": [
              {
                "to": [
                  {
                    "email": "${{ secrets.RECIPIENT }}"
                  }
                ],
                "subject": "polling email from ${{ github.action_repository }}"
              }
            ],
            "from": {
              "email": "${{ secrets.SENDER }}"
            },
            "content": [
              {
                "type": "text/plain",
                "value": "The scheduled GitHub action sends mails to keep your SendGrid account active.  For details, check out the repository ${{ github.action_repository }}."
              }
            ]
          }
          '
